"""initial migration

Revision ID: 86a0333d3b77
Revises: 
Create Date: 2026-04-08 11:59:01.768815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '86a0333d3b77'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_categories', sa.Column('category_name', sa.String(length=100), nullable=True))
    op.alter_column('assignment_categories', 'weight',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('assignment_categories', 'course_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'assignment_categories', 'courses', ['course_id'], ['course_id'])
    op.drop_column('assignment_categories', 'catergory_name')
    op.add_column('assignments', sa.Column('title', sa.String(length=225), nullable=True))
    op.add_column('assignments', sa.Column('course_id', sa.Integer(), nullable=True))
    op.add_column('assignments', sa.Column('category_id', sa.Integer(), nullable=True))
    op.alter_column('assignments', 'due_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               nullable=True)
    op.alter_column('assignments', 'assignment_type',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('assignments', 'score',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('assignments', 'max_score',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.create_foreign_key(None, 'assignments', 'assignment_categories', ['category_id'], ['category_id'])
    op.create_foreign_key(None, 'assignments', 'courses', ['course_id'], ['course_id'])
    op.drop_column('assignments', 'assignmentscol')
    op.alter_column('courses', 'course_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('courses', 'instructor',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('courses', 'student_user_name',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('students', 'student_user_name',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('students', 'goal_gpa',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'goal_gpa',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('students', 'student_user_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=False)
    op.alter_column('courses', 'student_user_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
    op.alter_column('courses', 'instructor',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
    op.alter_column('courses', 'course_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.add_column('assignments', sa.Column('assignmentscol', mysql.VARCHAR(length=45), nullable=False))
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.alter_column('assignments', 'max_score',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('assignments', 'score',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('assignments', 'assignment_type',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('assignments', 'due_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               nullable=False)
    op.drop_column('assignments', 'category_id')
    op.drop_column('assignments', 'course_id')
    op.drop_column('assignments', 'title')
    op.add_column('assignment_categories', sa.Column('catergory_name', mysql.VARCHAR(length=45), nullable=False))
    op.drop_constraint(None, 'assignment_categories', type_='foreignkey')
    op.alter_column('assignment_categories', 'course_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('assignment_categories', 'weight',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.drop_column('assignment_categories', 'category_name')
    # ### end Alembic commands ###
