"""Add firebase_uid and email to students

Revision ID: d8fc00df67e1
Revises: 
Create Date: 2026-04-11 12:42:44.543458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8fc00df67e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('firebase_uid', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'students', ['email'])
    op.create_unique_constraint(None, 'students', ['firebase_uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'firebase_uid')
    op.drop_column('students', 'email')
    # ### end Alembic commands ###
